package com.qrcodescanner.barcodereader.qrgenerator.utils

import com.qrcodescanner.barcodereader.qrgenerator.R
import com.qrcodescanner.barcodereader.qrgenerator.models.AllCountryModel


object CountryList {
    public fun getCountryList(): ArrayList<AllCountryModel> {
        val arrayList = ArrayList<AllCountryModel>()
        arrayList.add(AllCountryModel("English", R.drawable.united_states_of_america, "en", "en-US"))
        arrayList.add(AllCountryModel("Afrikaans", R.drawable.south_africa, "af", "af-ZA"))
        arrayList.add(AllCountryModel("Albanian", R.drawable.albania, "sq", "sq-AL"))
        arrayList.add(AllCountryModel("Amharic", R.drawable.ethiopia, "am", "am-ET"))
        arrayList.add(AllCountryModel("Arabic", R.drawable.ic_saudi_arabia, "ar", "ar-SA"))
        arrayList.add(AllCountryModel("Armenian", R.drawable.armenia, "hy", "hy-AM"))
        arrayList.add(AllCountryModel("Azerbaijani", R.drawable.azerbaijan, "az", "az-AZ"))
        arrayList.add(AllCountryModel("Basque", R.drawable.basque_country, "eu", "eu-ES"))
        arrayList.add(AllCountryModel("Bengali", R.drawable.bangladesh, "bn", "bn-BD"))
        arrayList.add(AllCountryModel("Bengali", R.drawable.india, "bn", "bn-IN"))
        arrayList.add(AllCountryModel("Bosnian", R.drawable.bosnia_and_herzegovina, "bs", "bs-BA"))
        arrayList.add(AllCountryModel("Bulgarian", R.drawable.bulgaria, "bg", "bg-BG"))
        arrayList.add(AllCountryModel("Burmese", R.drawable.myanmar, "my", "my-MM"))
        arrayList.add(AllCountryModel("Catalan", R.drawable.catalon, "ca", "ca-ES"))
        arrayList.add(AllCountryModel("Cebuano", R.drawable.philippines, "ceb", "ceb-PHL"))
        arrayList.add(AllCountryModel("Chinese Simplified", R.drawable.china, "zh", "zh-CN"))
        arrayList.add(AllCountryModel("Croatian", R.drawable.croatia, "hr", "hr-HR"))
        arrayList.add(AllCountryModel("Czech", R.drawable.czech_republic, "cs", "cs-CZ"))
        arrayList.add(AllCountryModel("Danish", R.drawable.denmark, "da", "da-DK"))
        arrayList.add(AllCountryModel("Dutch", R.drawable.belgium, "nl", "nl-BE"))
        arrayList.add(AllCountryModel("Esperanto", R.drawable.united_states_of_america, "eo", "eo-DZ"))
        arrayList.add(AllCountryModel("Estonian", R.drawable.estonia, "et", "et-EE"))
        arrayList.add(AllCountryModel("Filipino", R.drawable.philippines, "fil", "fil-PH"))
        arrayList.add(AllCountryModel("Finnish", R.drawable.finland, "fi", "fi-FI"))
        arrayList.add(AllCountryModel("French", R.drawable.france, "fr", "fr-FR"))
        arrayList.add(AllCountryModel("Frisian", R.drawable.germany, "fy", "fy-DEU"))
        arrayList.add(AllCountryModel("Galician", R.drawable.spain, "gl", "gl-ES"))
        arrayList.add(AllCountryModel("Georgian", R.drawable.georgia, "ka", "ka-GE"))
        arrayList.add(AllCountryModel("German", R.drawable.germany, "de", "de-DE"))
        arrayList.add(AllCountryModel("Greek", R.drawable.greece, "el", "el-GR"))
        arrayList.add(AllCountryModel("Gujarati", R.drawable.india, "gu", "gu-IN"))
        arrayList.add(AllCountryModel("Haitian", R.drawable.haiti, "ht", "ht-HTI"))
        arrayList.add(AllCountryModel("Hausa", R.drawable.hawaii, "ha", "ha-HUA"))
        arrayList.add(AllCountryModel("Hawaiian", R.drawable.united_states_of_america, "haw", "haw-US"))
        arrayList.add(AllCountryModel("Hindi", R.drawable.india, "hi", "hi-IN"))
        arrayList.add(AllCountryModel("Hmong", R.drawable.china, "hmn", "hmn-Hm"))
        arrayList.add(AllCountryModel("Hungarian", R.drawable.hungary, "hu", "hu-HU"))
        arrayList.add(AllCountryModel("Icelandic", R.drawable.iceland, "is", "is-IS"))
        arrayList.add(AllCountryModel("Indonesian", R.drawable.indonesia, "id", "id-ID"))
        arrayList.add(AllCountryModel("Italian", R.drawable.italy, "it", "it-IT"))
        arrayList.add(AllCountryModel("Japanese", R.drawable.japan, "ja", "ja-JP"))
        arrayList.add(AllCountryModel("Javanese", R.drawable.indonesia, "jv", "jv-ID"))
        arrayList.add(AllCountryModel("Kannada", R.drawable.ic_hindi, "kn", "kn-IN"))
        arrayList.add(AllCountryModel("Khmer", R.drawable.combodia_flag, "km", "km-IN"))
        arrayList.add(AllCountryModel("Korean", R.drawable.south_korea, "ko", "ko-KR"))
        arrayList.add(AllCountryModel("Kurdish", R.drawable.iran, "ku", "ku-KUR"))
        arrayList.add(AllCountryModel("Kyrgyz", R.drawable.kyrgyzstan, "ky", "ky-KGZ"))
        arrayList.add(AllCountryModel("Lao", R.drawable.laos, "lo", "lo-LA"))
        arrayList.add(AllCountryModel("Latvian", R.drawable.latvia, "lv", "lv-LV"))
        arrayList.add(AllCountryModel("Lithuanian", R.drawable.lithuania, "lt", "lt-LT"))
        arrayList.add(AllCountryModel("Macedonian", R.drawable.republic_of_macedonia, "mk", "mk-MK"))
        arrayList.add(AllCountryModel("Malagasy", R.drawable.united_states_of_america, "mg", "mg-MGD"))
        arrayList.add(AllCountryModel("Malay", R.drawable.malaysia, "ms", "ms-MY"))
        arrayList.add(AllCountryModel("Malayalam", R.drawable.india, "ml", "ml-IN"))
        arrayList.add(AllCountryModel("Maltese", R.drawable.malta, "mt", "mt-MLT"))
        arrayList.add(AllCountryModel("Maori", R.drawable.united_states_of_america, "mi", "mi-MIO"))
        arrayList.add(AllCountryModel("Marathi", R.drawable.india, "mr", "mr-IN"))
        arrayList.add(AllCountryModel("Mongolian", R.drawable.mongolia, "mn", "mn-MN"))
        arrayList.add(AllCountryModel("Myanmar", R.drawable.myanmar, "my", "my-MMR"))
        arrayList.add(AllCountryModel("Nepali", R.drawable.nepal, "ne", "ne-NP"))
        arrayList.add(AllCountryModel("Norwegian", R.drawable.norway, "no", "no-NO"))
        arrayList.add(AllCountryModel("Pashto", R.drawable.pakistan, "ps", "ps-PK"))
        arrayList.add(AllCountryModel("Persian", R.drawable.iran, "fa", "fa-FA"))
        arrayList.add(AllCountryModel("Polish", R.drawable.poland, "pl", "pl-PL"))
        arrayList.add(AllCountryModel("Portuguese", R.drawable.portuguese, "pt", "pt-BR"))
        arrayList.add(AllCountryModel("Punjabi", R.drawable.india, "pa", "pa-IN"))
        arrayList.add(AllCountryModel("Romanian", R.drawable.romania, "ro", "ro-RO"))
        arrayList.add(AllCountryModel("Russian", R.drawable.russia, "ru", "ru-RU"))
        arrayList.add(AllCountryModel("Samoan", R.drawable.samoa, "sm", "sm-WSM"))
        arrayList.add(AllCountryModel("Scots", R.drawable.scotland, "gd", "gd-GBR"))
        arrayList.add(AllCountryModel("Serbian", R.drawable.serbia, "sr", "sr-RS"))
        arrayList.add(AllCountryModel("Shona", R.drawable.zimbabwe, "sn", "sn-SNA"))
        arrayList.add(AllCountryModel("Sindhi", R.drawable.pakistan, "sd", "sd-Pk"))
        arrayList.add(AllCountryModel("Sinhala", R.drawable.sri_lanka, "si", "si-LK"))
        arrayList.add(AllCountryModel("Slovak", R.drawable.slovakia, "sk", "sk-SK"))
        arrayList.add(AllCountryModel("Slovenian", R.drawable.slovenia, "sl", "sl-SI"))
        arrayList.add(AllCountryModel("Somali", R.drawable.somalia, "so", "so-SOM"))
        arrayList.add(AllCountryModel("Spanish", R.drawable.spanish_flag, "es", "es-US"))
        arrayList.add(AllCountryModel("Sundanese", R.drawable.sudan, "su", "su-ID"))
        arrayList.add(AllCountryModel("Swahili", R.drawable.south_africa, "sw", "sw-SW"))
        arrayList.add(AllCountryModel("Swedish", R.drawable.sweden, "sv", "sv-SE"))
        arrayList.add(AllCountryModel("Tagalog", R.drawable.philippines, "tl", "tl-PH"))
        arrayList.add(AllCountryModel("Tajik", R.drawable.tajikistan, "tg", "tg-TG"))
        arrayList.add(AllCountryModel("Tamil", R.drawable.india, "ta", "ta-IN"))
        arrayList.add(AllCountryModel("Telugu", R.drawable.india, "te", "te-IN"))
        arrayList.add(AllCountryModel("Thai", R.drawable.thailand, "th", "th-TH"))
        arrayList.add(AllCountryModel("Turkish", R.drawable.turkey, "tr", "tr-TR"))
        arrayList.add(AllCountryModel("Ukrainian", R.drawable.ukraine, "uk", "uk-UA"))
        arrayList.add(AllCountryModel("Urdu", R.drawable.pakistan, "ur", "ur-PK"))
        arrayList.add(AllCountryModel("Uzbek", R.drawable.uzbekistn, "uz", "uz-UZ"))
        arrayList.add(AllCountryModel("Vietnamese", R.drawable.vietnam, "vi", "vi-VN"))
        arrayList.add(AllCountryModel("Welsh", R.drawable.wales, "cy", "cy-GB"))
        arrayList.add(AllCountryModel("Xhosa", R.drawable.south_africa, "xh", "xh-XH"))
        arrayList.add(AllCountryModel("Zulu", R.drawable.south_africa, "zu", "zu-ZU"))
        return arrayList
    }
}
